name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: DEPLOY

    runs-on: ubuntu-latest

    steps:
      - name: Deploy servidor Whatsapp
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST_DEPLOY }}
          USER: ${{ secrets.USER_DEPLOY }}
        with:
          args: |
            cd /var/www/whatsapp
            git add .
            git reset --hard
            git pull origin master
            npm install
            pm2 restart all
            exit
